"""add_cash_ledger

Revision ID: 9de55d44e0ad
Revises: d8a20f6527e2
Create Date: 2026-07-04 14:45:14.277158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de55d44e0ad'
down_revision = 'd8a20f6527e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_ledger',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID primary key'),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False, comment='Parent portfolio UUID'),
    sa.Column('transaction_id', sa.String(length=36), nullable=True, comment='Associated trade UUID (if any)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False, comment='Signed transaction amount in PKR (positive = cash-in, negative = cash-out)'),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'BUY', 'SELL', name='cash_ledger_type'), nullable=False, comment='Type of cash movement (DEPOSIT, WITHDRAWAL, BUY, SELL)'),
    sa.Column('transacted_at', sa.DateTime(timezone=True), nullable=False, comment='UTC datetime when the cash transaction occurred'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional description or details'),
    sa.CheckConstraint('amount != 0', name='ck_cash_ledger_amount_nonzero'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_ledger_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_ledger_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_ledger_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_cash_ledger_portfolio_id'))

    op.drop_table('cash_ledger')
    # ### end Alembic commands ###
