"""initial schema

Revision ID: d8a20f6527e2
Revises: 
Create Date: 2026-07-04 13:59:57.934910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a20f6527e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_prices',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID primary key'),
    sa.Column('ticker', sa.String(length=10), nullable=False, comment="PSX stock ticker symbol (uppercase, e.g. 'ENGRO')"),
    sa.Column('date', sa.Date(), nullable=False, comment='Trading session date (PST, no time component)'),
    sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=True, comment='Opening price in PKR'),
    sa.Column('high_price', sa.Numeric(precision=18, scale=4), nullable=True, comment='Intraday high price in PKR'),
    sa.Column('low_price', sa.Numeric(precision=18, scale=4), nullable=True, comment='Intraday low price in PKR'),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=False, comment='Closing price in PKR (required)'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='Total shares traded on this date'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this record was first inserted'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of the last upsert for this record'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_daily_prices_ticker_date')
    )
    with op.batch_alter_table('daily_prices', schema=None) as batch_op:
        batch_op.create_index('ix_daily_prices_ticker_date_desc', ['ticker', sa.literal_column('date DESC')], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID primary key'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Supabase auth.users UUID — owner of this portfolio'),
    sa.Column('name', sa.String(length=120), nullable=False, comment="Human-readable portfolio name (e.g. 'Long-term Holdings')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional free-text description'),
    sa.Column('initial_balance', sa.Numeric(precision=18, scale=4), nullable=False, comment='Initial cash balance in PKR at portfolio inception'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID primary key'),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False, comment='Parent portfolio UUID'),
    sa.Column('ticker', sa.String(length=10), nullable=False, comment="PSX stock ticker symbol (uppercase, e.g. 'ENGRO')"),
    sa.Column('action', sa.Enum('BUY', 'SELL', name='transaction_action'), nullable=False, comment='BUY or SELL'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Number of shares traded. Must be > 0.'),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False, comment='Price per share in PKR at execution. Must be > 0.'),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=False, comment='Broker commission in PKR (>= 0). Default is 0.'),
    sa.Column('transacted_at', sa.DateTime(timezone=True), nullable=False, comment='UTC datetime when the trade was executed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of record creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last update'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional trade note or rationale'),
    sa.CheckConstraint('commission >= 0', name='ck_transactions_commission_nonneg'),
    sa.CheckConstraint('price > 0', name='ck_transactions_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_transactions_quantity_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_transactions_portfolio_ticker_ts', ['portfolio_id', 'ticker', 'transacted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_portfolio_ticker_ts')
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('daily_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_prices_ticker_date_desc')

    op.drop_table('daily_prices')
    # ### end Alembic commands ###
