"""add company_metadata

Revision ID: e1c45f847e71
Revises: 6d462f2450ec
Create Date: 2026-07-04 15:40:58.935149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c45f847e71'
down_revision = '6d462f2450ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_metadata',
    sa.Column('ticker', sa.String(length=20), nullable=False, comment="Ticker symbol (e.g. 'ENGRO')"),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment="Official company name (e.g. 'Engro Corporation Limited')"),
    sa.Column('sector', sa.String(length=100), nullable=False, comment="PSX industry sector (e.g. 'FERTILIZER')"),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('company_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_metadata_sector'), ['sector'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_metadata_sector'))

    op.drop_table('company_metadata')
    # ### end Alembic commands ###
